# Generated by Django 5.2.6 on 2025-11-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="fabricante",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="modelo",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="numero_serie",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="herramienta",
            index=models.Index(
                fields=["fabricante", "modelo"], name="herramienta_fab_modelo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="herramienta",
            index=models.Index(fields=["ubicacion"], name="herramienta_ubicacion_idx"),
        ),
        migrations.AddIndex(
            model_name="ubicacion",
            index=models.Index(
                fields=["nave", "banda"], name="ubicacion_nave_banda_idx"
            ),
        ),
    ]
