# Generated by Django 5.2.6 on 2025-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='ejecucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
