# Generated by Django 5.2.6 on 2025-11-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_herramienta_fabricante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herramienta",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
