# Generated by Django 5.2.6 on 2025-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_herramienta_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sap",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número SAP",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.IntegerField(default=0, verbose_name="Cantidad en Stock"),
                ),
                (
                    "ubicacion_almacen",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ubicación en Almacén",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Proveedor"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Refacción",
                "verbose_name_plural": "Refacciones",
                "ordering": ["numero_sap"],
                "indexes": [
                    models.Index(fields=["numero_sap"], name="refaccion_sap_idx"),
                    models.Index(fields=["descripcion"], name="refaccion_desc_idx"),
                ],
            },
        ),
    ]
