# Generated by Django 5.2.6 on 2025-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_refaccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="refaccion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="refacciones/",
                verbose_name="Imagen/Fotografía",
            ),
        ),
    ]
