# Generated by Django 5.2.6 on 2025-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Mantenimiento, Líderes de Línea', max_length=100, unique=True)),
                ('miembros', models.ManyToManyField(related_name='grupos_notificacion', to='usuarios.colaborador')),
            ],
            options={
                'verbose_name': 'Grupo de Notificación',
                'verbose_name_plural': 'Grupos de Notificación',
            },
        ),
    ]
