# Generated by Django 5.2.6 on 2025-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaticket',
            name='operacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='auditoriaticket',
            name='tacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tacto'),
        ),
    ]
