# Generated by Django 5.2.6 on 2025-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auditoriaticket_operacion_auditoriaticket_tacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno'),
        ),
    ]
