# Generated by Django 5.2.6 on 2025-11-24 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_herramienta_fabricante_and_more"),
        ("tickets", "0002_comentario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditoriaticket",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Auditoría de Ticket",
                "verbose_name_plural": "Auditorías de Tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="comentario",
            options={
                "ordering": ["fecha_creacion"],
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AddIndex(
            model_name="auditoriaticket",
            index=models.Index(
                fields=["ticket", "-fecha"], name="audit_ticket_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comentario",
            index=models.Index(
                fields=["ticket", "fecha_creacion"], name="comment_ticket_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario_destino", "leido", "-fecha_creacion"],
                name="notif_usuario_leido_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(fields=["ticket"], name="notif_ticket_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["-fecha_creacion"], name="ticket_fecha_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["estado", "-fecha_creacion"], name="ticket_estado_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["herramienta"], name="ticket_herramienta_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["creado_por", "-fecha_creacion"], name="ticket_usuario_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["folio"], name="ticket_folio_idx"),
        ),
    ]
